export enum RouteNames {
	ROOT = "ROOT",
	AUTH = "AUTH",
	AUTH_LOGIN_PAGE = "AUTH_LOGIN_PAGE",
	TABS = "TABS",
	HOME = "HOME",
	TEST = "TEST",
	ERROR_INTERNAL_SERVER_ERROR = "ERROR_INTERNAL_SERVER_ERROR",
	ERROR_ACCESS_DENIED = "ERROR_ACCESS_DENIED",
	ERROR_PAGE_NOT_FOUND = "ERROR_PAGE_NOT_FOUND"
}
